### ISSUE TITLE
json-schema unmaintained and fails to build on ruby 2.7

### ISSUE THREAD

**Issue by lelutin** [voxpupuli/metadata-json-lint#105]
Hello,

I'm currently working on getting pdk (and thus metadata-json-lint too as a dependency) packaged for debian. I was told that during the just-finished dev sprint of the debian ruby team (working on transitioning debian testing to ruby 2.7), it was found that the json-schema library fails to build from source with ruby 2.7

Info about the failure can be found here:

https://people.debian.org/~kanashiro/ruby2.7/builds/7/ruby-json-schema/ruby-json-schema_2.8.1-1+rebuild1580878603_amd64-2020-02-05T04:56:44Z.build.txt

it was brought to my attention that the json-schema library has been unmaintained for a while now. this upstream ticket about trying to find new maintainers mentions some alternative libraries that can be used instead:

ruby-json-schema/json-schema#423

So, for the future maintainability of metadata-json-lint, it might be worthwhile to consider switching this library for another one offering similar functionality.

I've already reported the same issue with PDK which also directly depends on json-schema, and upstream told me that the dependency to the json-schema library will be removed in pdk 2.0.0

https://github.com/puppetlabs/pdk/issues/848

Cheers!

**Comment by bastelfreak** [comment]
Hi @lelutin. I also try to package pdk, but for Arch and I'm running into the same issue. The fix from https://github.com/ruby-json-schema/json-schema/pull/437 works for me on ruby 2.7. However, switching to the other library mentioned in https://github.com/ruby-json-schema/json-schema/issues/423 would be nice. Sadly I don't have the time at the moment to invest more time into metadata-json-lint :(

**Comment by lelutin** [comment]
@bastelfreak thanks for the hint! we'll try applying the patch to the debian json-schema package to see if it avoids the issue with 2.7.
it's a generally better idea to switch to something that's maintained, but if it can give us a bit more time before doing the switch then maybe we can still have things that depend on json-schema working for a while. :+1:

**Comment by ekohl** [comment]
Closing this since the issues should be filed in https://github.com/voxpupuli/json-schema.
