### ISSUE TITLE
For the license: missing a file and license headers in source files

### ISSUE THREAD

**Issue by lelutin** [voxpupuli/metadata-json-lint#115]
Hello,

While scrutinizing this project for creating a package for debian with it, I noticed some details that seem to be missing according to the license that you've chosen for the code:

* There needs to be a NOTICE file at the top level
* Each source code file should have a header comment mentioning the license and a copyright attribution

You can find more details about those two points in the following URL: https://infra.apache.org/apply-license.html

**Comment by alexjfisher** [comment]
Those instructions seem to be specific to the Apache organisation applying the Apache licence to their products.

**Comment by lelutin** [comment]
hmm .. you're right. I looked up in the license text and the presence of the NOTICE file is optional (but if present needs to be kept around).

I'm sorry for the noise then. I'll fix my notes about this license to stop bothering ppl :\

**Comment by alexjfisher** [comment]
No worries.  We're actually very keen to have closer relationships with packagers.  Stop by #voxpupuli on Freenode IRC if you want to introduce yourself or have any questions we can help with.
