### ISSUE TITLE
Missing possibility to set options via spec_helper.rb like rspec

### ISSUE THREAD

**Issue by tuxinaut** [voxpupuli/metadata-json-lint#18]
I miss the possibility to set options via spec_helper.rb like rspec do it.

```
MetadataJsonLint.configure do |c|
  c.strict_license = false
end
```

**Comment by electrical** [comment]
This is something I started to work on today.
Does require some refactoring of the code but shouldn't be to hard to do.
Will update the thread once i got something working.

**Comment by nibalizer** [comment]
@electrical how far did you get? Want to open a WIP branch and maybe someone else can pick it up?

**Comment by electrical** [comment]
Haven't gotten around to it still :-( darn work keeps bugging me with other things.

**Comment by rmestrum** [comment]
@electrical do you have an update?

**Comment by seanmalloy** [comment]
@electrical any updates? Would you be able to open a WIP branch?

I'd be willing to try and assist if you could push your branch.

**Comment by tuxinaut** [comment]
Looks like it is fixed, so I'm going to close the pull request.
