### ISSUE TITLE
Automate rubygems publishing

### ISSUE THREAD

**Issue by nibalizer** [voxpupuli/metadata-json-lint#20]
@raphink could you help me get rubygems going on this via travis?

**Comment by igalic** [comment]
@raphink ping

**Comment by ffrank** [comment]
More pings for @raphink.

**Comment by raphink** [comment]
I'll try to look into it this morning.

**Comment by raphink** [comment]
@nibalizer still want to look into that?

**Comment by nibalizer** [comment]
Ya!

**Comment by igalic** [comment]
bump

**Comment by igalic** [comment]
gosh, i really wish we had more time.
or a couple of @ffrank, @nibalizer, et al clones

**Comment by nibalizer** [comment]
OH RIGHT THIS

**Comment by igalic** [comment]
AND ALL THE OTHER PLUMBING ISSUES…

**Comment by nibalizer** [comment]
#puppethack

**Comment by nibalizer** [comment]
For anyone playing along at home: @igalic and @raphink now have permission to push to this gem.

**Comment by raphink** [comment]
Thanks @nibalizer. I'll add a deploy statement in .travis.yml to automate publishing

**Comment by raphink** [comment]
https://github.com/puppet-community/metadata-json-lint/commit/575420f268bae4cc601de96da3fe0704163963fa does that. Now tagging and pushing should automatically release to rubygems. Next release will tell if that works ;-)

**Comment by igalic** [comment]
\o/

**Comment by nibalizer** [comment]
@raphink I attempted several times today to push tags. You can see the results in travis. It did not upload to rubygems :(

**Comment by raphink** [comment]
I'll check @nibalizer

**Comment by raphink** [comment]
The error says "ERROR:  Gemspec file not found: metadata-json-lint.gemspec"

**Comment by nibalizer** [comment]
Right but, there is a gemspec file. So what is the issue?

**Comment by rnelson0** [comment]
The issue was the travis tests left us in the wrong directory to find the gemspec. Whoops! This has been resolved, finally!
