### ISSUE TITLE
Open-ended dependency warnings

### ISSUE THREAD

**Issue by ZeroPointEnergy** [voxpupuli/metadata-json-lint#24]
It would be nice if metadata-json-lint warns about open-ended dependencies like gem does. To have version boundaries for all dependencies to signal the user what versions are compatible and tested is an important quality criteria in my opinion.

Example from gem:
`
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
`

**Comment by igalic** [comment]
yes, please :D

**Comment by electrical** [comment]
We had this in the past via https://github.com/voxpupuli/metadata-json-lint/pull/9 but had to be reverted because of some conflicts.
We should revisit this indeed.

**Comment by 3flex** [comment]
I opened PR #25, please take a look and let me know if you have any feedback.
