### ISSUE TITLE
Post latest release grouped rake tasks exits after running metadata_lint task.

### ISSUE THREAD

**Issue by shaheed121** [voxpupuli/metadata-json-lint#70]
After the latest update grouped rake tasks exit just after running metadata_lint task without any error. In the case below `rake validation` task exits just after running metadata_lint without running the syntax task.

```
desc 'Validate json hieradata'
JsonLint::RakeTask.new do |task|
  task.paths = ['data/**/*.json']
end

desc 'validation'
task :validation do
  Rake::Task[:jsonlint].invoke
  Rake::Task[:metadata_lint].invoke
  Rake::Task[:syntax].invoke
end
```

**Comment by luyseyal** [comment]
We also have this issue. Hoping you can prioritize a release. We've pinned to 1.1.0 in the meantime.

**Comment by davidmogar** [comment]
When are releasing a new version with this patch?

**Comment by domcleal** [comment]
I've opened a PR to issue a release at #73.
