### ISSUE TITLE
Current version of the Gem is Ruby >= 2 only

### ISSUE THREAD

**Issue by lazyfrosch** [voxpupuli/metadata-json-lint#74]
There is a syntax issue with Ruby < 2
```
SyntaxError: /.../vendor/bundle/ruby/1.9.1/gems/metadata-json-lint-1.2.2/lib/metadata_json_lint.rb:39: unknown type of %string
...on('-f', '--format FORMAT', %i[text json], 'The format in wh...
...                               ^
```
I had to pin the gem to 1.1 to fix it.

**Comment by lazyfrosch** [comment]
Intended or not? If so, the Gem should say Ruby >= 2

**Comment by domcleal** [comment]
> Intended or not? If so, the Gem should say Ruby >= 2

Yes, the gemspec should state the minimum version. Currently it's documented at https://github.com/voxpupuli/metadata-json-lint#compatibility.
