### ISSUE TITLE
Validate puppet version_requirement

### ISSUE THREAD

**Issue by dhollinger** [voxpupuli/metadata-json-lint#99]
Add validation that will parse the `puppet` version requirement and validate it against the following parameters:

* It is a valid SemVer formatted version number.
* It is within the range of supported Puppet versions.

**Comment by ghoneycutt** [comment]
+1 to the first bit about semver validation.

The second piece should be its own issue.

**Comment by ekohl** [comment]
It should also check if it has the correct key(s). I've seen `requirement` vs `requirements` which is a subtle thing to miss.

**Comment by dhollinger** [comment]
@ghoneycutt @ekhol - looks like the first bullet is already accounted for in the gem. #100 addresses the second issue
